import type { ModuleDefinition } from "./module-catalog";

export const DefaultModuleCatalog = [
  {
    id: "app-shell.sidebar-dashboard",
    version: "1.1.0",
    family: "app-shell",
    name: "Adaptive Product Shell",
    description: "Application shell patterns for product workspaces, dashboards and command surfaces.",
    intentTags: ["app-shell", "sidebar", "workspace", "dashboard", "command-center"],
    useWhen: ["The screen needs persistent navigation, workspace context or operational command structure."],
    avoidWhen: ["The prompt asks for a standalone marketing page, auth flow or simple content page."],
    deviceSupport: ["desktop", "tablet"],
    slots: [
      { id: "primary-nav", required: true, accepts: ["nav-item"], minItems: 3, maxItems: 10 },
      { id: "context-bar", required: false, accepts: ["search", "button", "avatar", "status"], maxItems: 6 },
      { id: "workspace", required: true, accepts: ["dashboard", "table", "form", "panel"] },
      { id: "secondary-panel", required: false, accepts: ["inspector", "activity-feed", "details"], maxItems: 2 },
    ],
    variants: [
      {
        id: "compact-ops",
        label: "Compact Ops Shell",
        density: "compact",
        composition: "Narrow sidebar, compressed topbar, status strip and a data-heavy content region.",
        bestFor: ["operations", "monitoring", "admin tools"],
        promptSignals: ["dense", "compact", "ops", "admin", "monitoring"],
        variationAxes: {
          hierarchy: "navigation-led",
          navigation: "narrow sidebar",
          contentVolume: "high",
          visualTone: "calm technical",
        },
      },
      {
        id: "inspector-workbench",
        label: "Inspector Workbench",
        density: "comfortable",
        composition: "Split workspace with left rail, central canvas/list and right inspector panel.",
        bestFor: ["design tools", "builder interfaces", "review workflows"],
        promptSignals: ["split-pane", "inspector", "canvas", "workbench", "command actions"],
        variationAxes: {
          hierarchy: "object-led",
          navigation: "rail plus inspector",
          contentVolume: "medium",
          visualTone: "builder-grade",
        },
      },
      {
        id: "mission-control",
        label: "Mission Control",
        density: "compact",
        composition: "Status wall with horizontal command bar, priority lanes and live operational panels.",
        bestFor: ["incident rooms", "logistics", "support operations"],
        promptSignals: ["mission control", "war room", "status board", "escalation", "live queue"],
        variationAxes: {
          hierarchy: "status-led",
          navigation: "command bar",
          contentVolume: "high",
          visualTone: "urgent restrained",
        },
      },
      {
        id: "narrative-rail",
        label: "Narrative Rail",
        density: "spacious",
        composition: "Content-first workspace with a slim contextual rail and chronological decision trail.",
        bestFor: ["strategy rooms", "research reviews", "executive storytelling"],
        promptSignals: ["story", "narrative", "timeline", "briefing", "research"],
        variationAxes: {
          hierarchy: "narrative-led",
          navigation: "context rail",
          contentVolume: "medium",
          visualTone: "editorial product",
        },
      },
    ],
    selectionHeuristics: {
      positivePromptSignals: [
        "dashboard",
        "workspace",
        "sidebar",
        "admin",
        "saas",
        "workbench",
        "mission control",
        "inspector",
      ],
      negativePromptSignals: ["landing", "pricing", "login", "signup"],
      compatibleFamilies: ["dashboard", "data-display", "form", "feedback"],
      incompatibleFamilies: ["marketing", "pricing", "auth"],
    },
    designSpecHints: {
      allowedNodeTypes: ["frame", "stack", "nav", "text", "button", "input", "card"],
      maxDepth: 8,
      responsiveBehavior: [
        "Collapse secondary panels before primary navigation.",
        "Preserve the active object or status lane on tablet.",
      ],
    },
    shadcnHints: {
      primitives: ["Sidebar", "Button", "Avatar", "Input", "Resizable"],
      registryItems: ["sidebar", "button", "avatar", "input", "resizable"],
      compositionNotes: ["Use Sidebar for persistent navigation and Resizable for inspector layouts."],
    },
    accessibilityNotes: ["Collapsed navigation must retain text labels through accessible names."],
  },
  {
    id: "dashboard.metric-overview",
    version: "1.1.0",
    family: "dashboard",
    name: "Metric Intelligence Surface",
    description: "Dashboard compositions for metrics, incidents, forecasts and decision reviews.",
    intentTags: ["dashboard", "metrics", "monitoring", "analytics", "command-center"],
    useWhen: ["The prompt asks for metrics, monitoring, analytics, status overview or operational intelligence."],
    avoidWhen: ["The prompt primarily asks for settings, auth, pricing or editorial content."],
    deviceSupport: ["desktop", "tablet", "mobile"],
    slots: [
      { id: "metrics", required: true, accepts: ["stat-card"], minItems: 3, maxItems: 8 },
      { id: "primary-visualization", required: true, accepts: ["chart", "table", "timeline"] },
      { id: "supporting-data", required: false, accepts: ["table", "activity-feed", "status-board"], maxItems: 3 },
    ],
    variants: [
      {
        id: "incident-command",
        label: "Incident Command",
        density: "compact",
        composition: "Live incident queue, severity lanes, service health strip and action-focused metrics.",
        bestFor: ["incident response", "monitoring", "support escalation"],
        promptSignals: ["incident", "escalation", "status board", "live queue", "command center"],
        variationAxes: {
          hierarchy: "status-led",
          navigation: "severity lanes",
          contentVolume: "high",
          visualTone: "calm urgent",
        },
      },
      {
        id: "executive-story",
        label: "Executive Story",
        density: "spacious",
        composition: "Board-ready metric story with headline insight, trend panels and annotated exceptions.",
        bestFor: ["executive dashboard", "weekly reporting", "board review"],
        promptSignals: ["executive", "board", "reporting", "summary", "weekly"],
        variationAxes: {
          hierarchy: "insight-led",
          navigation: "topbar",
          contentVolume: "medium",
          visualTone: "strategic enterprise",
        },
      },
      {
        id: "revenue-radar",
        label: "Revenue Radar",
        density: "comfortable",
        composition: "Funnel, cohort and pipeline cards orbiting a forecast chart with risk callouts.",
        bestFor: ["sales analytics", "growth", "finance dashboards"],
        promptSignals: ["revenue", "pipeline", "forecast", "funnel", "cohort"],
        variationAxes: {
          hierarchy: "forecast-led",
          navigation: "segmented controls",
          contentVolume: "medium",
          visualTone: "commercial analytical",
        },
      },
      {
        id: "lab-bench",
        label: "Experiment Lab Bench",
        density: "compact",
        composition: "Experiment cards, confidence bands, variant comparison and decision queue.",
        bestFor: ["A/B testing", "product experiments", "model evaluations"],
        promptSignals: ["experiment", "ab test", "variant", "confidence", "evaluation"],
        variationAxes: {
          hierarchy: "comparison-led",
          navigation: "tabs",
          contentVolume: "high",
          visualTone: "scientific product",
        },
      },
    ],
    selectionHeuristics: {
      positivePromptSignals: [
        "dashboard",
        "metrics",
        "analytics",
        "monitoring",
        "kpi",
        "incident",
        "revenue",
        "experiment",
      ],
      negativePromptSignals: ["login", "pricing", "checkout"],
      compatibleFamilies: ["app-shell", "data-display", "feedback"],
      incompatibleFamilies: ["auth", "pricing"],
    },
    designSpecHints: {
      allowedNodeTypes: ["frame", "stack", "card", "chart", "table", "text"],
      maxDepth: 8,
      responsiveBehavior: ["Stack metric groups before hiding supporting data.", "Convert wide comparison areas to sections on mobile."],
    },
    shadcnHints: {
      primitives: ["Card", "Chart", "Table", "Badge", "Tabs"],
      registryItems: ["card", "chart", "table", "badge", "tabs"],
      compositionNotes: ["Use Card for metric containers and Tabs for experiment or segment switching."],
    },
    accessibilityNotes: ["Charts require adjacent textual summaries and status must not rely only on color."],
  },
  {
    id: "data-display.table-with-filters",
    version: "1.1.0",
    family: "data-display",
    name: "Structured Data Workbench",
    description: "Data-heavy surfaces for filtering, comparing, triaging and auditing records.",
    intentTags: ["table", "filters", "data", "records", "comparison"],
    useWhen: ["The user asks to browse, manage, compare, audit or filter many records."],
    avoidWhen: ["The screen is primarily a landing page, auth page or simple empty state."],
    deviceSupport: ["desktop", "tablet"],
    slots: [
      { id: "toolbar", required: true, accepts: ["search", "filter", "button"], minItems: 2, maxItems: 6 },
      { id: "columns", required: true, accepts: ["table-column"], minItems: 3, maxItems: 10 },
      { id: "record-actions", required: false, accepts: ["button", "menu", "bulk-action"], maxItems: 4 },
    ],
    variants: [
      {
        id: "ops-table",
        label: "Ops Table",
        density: "compact",
        composition: "Dense rows, status badges, saved filters, bulk actions and row-level menus.",
        bestFor: ["admin records", "monitoring queues", "support inboxes"],
        promptSignals: ["table", "filter", "records", "admin", "bulk"],
        variationAxes: {
          hierarchy: "table-led",
          navigation: "toolbar",
          contentVolume: "high",
          visualTone: "technical utility",
        },
      },
      {
        id: "comparison-matrix",
        label: "Comparison Matrix",
        density: "comfortable",
        composition: "Pinned comparison columns, score bands and decision annotations.",
        bestFor: ["vendor comparison", "feature matrix", "plan comparison"],
        promptSignals: ["compare", "comparison", "matrix", "score", "evaluate"],
        variationAxes: {
          hierarchy: "comparison-led",
          navigation: "pinned columns",
          contentVolume: "medium",
          visualTone: "analytical",
        },
      },
      {
        id: "kanban-triage",
        label: "Kanban Triage",
        density: "compact",
        composition: "Filtered table alternative with lanes, cards, SLA badges and queue counters.",
        bestFor: ["support triage", "incident queue", "review workflow"],
        promptSignals: ["kanban", "triage", "queue", "lane", "sla"],
        variationAxes: {
          hierarchy: "workflow-led",
          navigation: "lanes",
          contentVolume: "high",
          visualTone: "operations",
        },
      },
      {
        id: "evidence-ledger",
        label: "Evidence Ledger",
        density: "comfortable",
        composition: "Audit-grade record list with provenance, timestamps, filters and expandable evidence.",
        bestFor: ["audit logs", "compliance", "security reviews"],
        promptSignals: ["audit", "ledger", "evidence", "compliance", "provenance"],
        variationAxes: {
          hierarchy: "evidence-led",
          navigation: "filters plus timeline",
          contentVolume: "medium",
          visualTone: "trustworthy restrained",
        },
      },
    ],
    selectionHeuristics: {
      positivePromptSignals: [
        "table",
        "filter",
        "records",
        "list",
        "manage",
        "compare",
        "kanban",
        "audit",
      ],
      negativePromptSignals: ["hero", "login", "pricing"],
      compatibleFamilies: ["app-shell", "dashboard", "feedback"],
      incompatibleFamilies: ["auth", "marketing"],
    },
    designSpecHints: {
      allowedNodeTypes: ["frame", "stack", "table", "input", "button", "text", "card"],
      maxDepth: 7,
      responsiveBehavior: ["Prioritize key identifiers and status columns.", "Use stacked record cards on mobile later."],
    },
    shadcnHints: {
      primitives: ["Table", "Input", "Button", "DropdownMenu", "Badge", "Tabs"],
      registryItems: ["table", "input", "button", "dropdown-menu", "badge", "tabs"],
      compositionNotes: ["Use Table for records, DropdownMenu for row actions and Tabs for saved views."],
    },
    accessibilityNotes: ["Filter controls need labels and record status must not rely only on color."],
  },
  {
    id: "form.settings-form",
    version: "1.1.0",
    family: "form",
    name: "Configuration Flow",
    description: "Form patterns for settings, onboarding, policies and live configuration previews.",
    intentTags: ["form", "settings", "profile", "configuration", "workflow"],
    useWhen: ["The prompt asks for account, workspace, billing, security, onboarding or configuration settings."],
    avoidWhen: ["The prompt asks for dashboards, marketing pages or data-heavy tables."],
    deviceSupport: ["desktop", "tablet", "mobile"],
    slots: [
      { id: "sections", required: true, accepts: ["field-group"], minItems: 2, maxItems: 7 },
      { id: "save-actions", required: true, accepts: ["button"], minItems: 1, maxItems: 3 },
      { id: "assistive-panel", required: false, accepts: ["preview", "summary", "help"], maxItems: 2 },
    ],
    variants: [
      {
        id: "sectioned-page",
        label: "Sectioned Page",
        density: "comfortable",
        composition: "Stacked settings sections with descriptions, validation space and save bar.",
        bestFor: ["account settings", "workspace preferences"],
        promptSignals: ["settings", "preferences", "profile", "account"],
        variationAxes: {
          hierarchy: "form-led",
          navigation: "section stack",
          contentVolume: "medium",
          visualTone: "quiet utility",
        },
      },
      {
        id: "guided-wizard",
        label: "Guided Wizard",
        density: "spacious",
        composition: "Multi-step setup flow with progress, checkpoints and contextual help.",
        bestFor: ["onboarding", "setup", "guided configuration"],
        promptSignals: ["wizard", "onboarding", "setup", "step-by-step", "guided"],
        variationAxes: {
          hierarchy: "progress-led",
          navigation: "stepper",
          contentVolume: "medium",
          visualTone: "supportive product",
        },
      },
      {
        id: "policy-console",
        label: "Policy Console",
        density: "compact",
        composition: "Rule groups, toggles, exceptions and review summary for admin-grade policies.",
        bestFor: ["security policy", "permissions", "compliance settings"],
        promptSignals: ["policy", "permissions", "security", "rules", "exceptions"],
        variationAxes: {
          hierarchy: "rules-led",
          navigation: "settings-sidebar",
          contentVolume: "high",
          visualTone: "enterprise governance",
        },
      },
      {
        id: "live-preview-config",
        label: "Live Preview Config",
        density: "comfortable",
        composition: "Form on one side with real-time preview, summary and publish controls on the other.",
        bestFor: ["theme settings", "template editors", "notification builders"],
        promptSignals: ["preview", "theme", "template", "builder", "publish"],
        variationAxes: {
          hierarchy: "preview-led",
          navigation: "split panel",
          contentVolume: "medium",
          visualTone: "craft tool",
        },
      },
    ],
    selectionHeuristics: {
      positivePromptSignals: [
        "settings",
        "preferences",
        "profile",
        "configuration",
        "account",
        "wizard",
        "policy",
        "preview",
      ],
      negativePromptSignals: ["dashboard", "pricing", "landing"],
      compatibleFamilies: ["app-shell", "settings", "feedback"],
      incompatibleFamilies: ["marketing", "pricing"],
    },
    designSpecHints: {
      allowedNodeTypes: ["frame", "stack", "card", "text", "input", "button"],
      maxDepth: 8,
      responsiveBehavior: ["Stack sections on mobile.", "Keep save or continue action visible after fields."],
    },
    shadcnHints: {
      primitives: ["Field", "Input", "Select", "Switch", "Button", "Card", "Tabs"],
      registryItems: ["field", "input", "select", "switch", "button", "card", "tabs"],
      compositionNotes: ["Use Field groups for form layout and Tabs or stepper-like structure for segmented flows."],
    },
    accessibilityNotes: ["Every input needs an accessible label and validation text location."],
  },
  {
    id: "feedback.empty-state-action",
    version: "1.1.0",
    family: "feedback",
    name: "Activation Empty State",
    description: "Empty states that turn missing data into a clear next action or onboarding path.",
    intentTags: ["empty-state", "onboarding", "feedback", "action", "activation"],
    useWhen: ["The screen has no records, needs onboarding or the prompt lacks enough data."],
    avoidWhen: ["The user asks for dense populated dashboards or tables."],
    deviceSupport: ["desktop", "tablet", "mobile"],
    slots: [
      { id: "message", required: true, accepts: ["text"], minItems: 1, maxItems: 3 },
      { id: "primary-action", required: true, accepts: ["button"], minItems: 1, maxItems: 1 },
      { id: "secondary-actions", required: false, accepts: ["button", "link"], maxItems: 2 },
      { id: "supporting-proof", required: false, accepts: ["tip", "checklist", "sample"], maxItems: 3 },
    ],
    variants: [
      {
        id: "launchpad",
        label: "Launchpad",
        density: "comfortable",
        composition: "Centered activation panel with first action, example chips and confidence-building hints.",
        bestFor: ["new projects", "first-run workflows"],
        promptSignals: ["first run", "start", "launch", "create", "new project"],
        variationAxes: {
          hierarchy: "action-led",
          navigation: "none",
          contentVolume: "low",
          visualTone: "confident helpful",
        },
      },
      {
        id: "contextual-inline",
        label: "Contextual Inline",
        density: "compact",
        composition: "Embedded empty panel inside a table or dashboard with targeted action and help link.",
        bestFor: ["empty tables", "empty dashboard widgets"],
        promptSignals: ["empty table", "no records", "inline", "no results"],
        variationAxes: {
          hierarchy: "context-led",
          navigation: "embedded",
          contentVolume: "low",
          visualTone: "quiet utility",
        },
      },
      {
        id: "idea-wall",
        label: "Idea Wall",
        density: "spacious",
        composition: "Prompt starter wall with example directions, sample cards and exploration CTA.",
        bestFor: ["AI tools", "creative starts", "prompt-first products"],
        promptSignals: ["ideas", "prompt", "inspiration", "examples", "explore"],
        variationAxes: {
          hierarchy: "inspiration-led",
          navigation: "sample cards",
          contentVolume: "medium",
          visualTone: "creative product",
        },
      },
      {
        id: "checklist-onboarding",
        label: "Checklist Onboarding",
        density: "comfortable",
        composition: "Empty state paired with a short checklist, progress hint and next best action.",
        bestFor: ["setup checklists", "team onboarding", "activation funnels"],
        promptSignals: ["checklist", "onboarding", "setup", "progress", "activation"],
        variationAxes: {
          hierarchy: "progress-led",
          navigation: "checklist",
          contentVolume: "medium",
          visualTone: "guided practical",
        },
      },
    ],
    selectionHeuristics: {
      positivePromptSignals: [
        "empty",
        "no data",
        "first run",
        "onboarding",
        "create",
        "ideas",
        "checklist",
      ],
      negativePromptSignals: ["dense", "metrics", "populated"],
      compatibleFamilies: ["app-shell", "data-display", "dashboard", "form"],
      incompatibleFamilies: ["pricing"],
    },
    designSpecHints: {
      allowedNodeTypes: ["frame", "stack", "card", "text", "button", "icon"],
      maxDepth: 6,
      responsiveBehavior: ["Keep copy concise on mobile.", "Place primary action after explanation."],
    },
    shadcnHints: {
      primitives: ["Empty", "Button", "Card", "Badge"],
      registryItems: ["empty", "button", "card", "badge"],
      compositionNotes: ["Use Empty for standalone states and Card for embedded states."],
    },
    accessibilityNotes: ["The empty state must state what happened and what action is available."],
  },
  {
    id: "feedback.error-state-retry",
    version: "1.1.0",
    family: "feedback",
    name: "Recovery State",
    description: "Recoverable failure states for inline errors, outages, diagnostics and graceful degradation.",
    intentTags: ["error", "retry", "failure", "feedback", "diagnostic"],
    useWhen: ["The screen needs to represent failed loading, validation, connection or degraded service states."],
    avoidWhen: ["The prompt asks for a happy-path marketing or dashboard-only view."],
    deviceSupport: ["desktop", "tablet", "mobile"],
    slots: [
      { id: "error-message", required: true, accepts: ["text"], minItems: 1, maxItems: 3 },
      { id: "recovery-actions", required: true, accepts: ["button"], minItems: 1, maxItems: 3 },
      { id: "details", required: false, accepts: ["text", "code", "timeline"], maxItems: 3 },
    ],
    variants: [
      {
        id: "inline-retry",
        label: "Inline Retry",
        density: "compact",
        composition: "Inline panel with error summary, retry button, support action and last-updated note.",
        bestFor: ["table load failure", "widget failure", "API retry"],
        promptSignals: ["retry", "inline", "failed load", "widget", "try again"],
        variationAxes: {
          hierarchy: "recovery-led",
          navigation: "embedded",
          contentVolume: "low",
          visualTone: "direct",
        },
      },
      {
        id: "outage-command",
        label: "Outage Command",
        density: "compact",
        composition: "Page-level outage panel with service status, incident timeline and escalation actions.",
        bestFor: ["service outage", "incident communication", "system unavailable"],
        promptSignals: ["outage", "unavailable", "incident", "status page", "escalate"],
        variationAxes: {
          hierarchy: "status-led",
          navigation: "timeline",
          contentVolume: "medium",
          visualTone: "transparent calm",
        },
      },
      {
        id: "diagnostic-console",
        label: "Diagnostic Console",
        density: "compact",
        composition: "Technical failure view with checks, logs summary and recommended remediation path.",
        bestFor: ["developer tools", "admin diagnostics", "integration failures"],
        promptSignals: ["diagnostic", "logs", "debug", "checks", "integration"],
        variationAxes: {
          hierarchy: "diagnostic-led",
          navigation: "checklist",
          contentVolume: "high",
          visualTone: "developer utility",
        },
      },
      {
        id: "graceful-degrade",
        label: "Graceful Degrade",
        density: "comfortable",
        composition: "Partial content shell showing available data, disabled areas and recovery guidance.",
        bestFor: ["partial outages", "offline mode", "degraded dashboards"],
        promptSignals: ["offline", "degraded", "partial", "fallback", "limited"],
        variationAxes: {
          hierarchy: "continuity-led",
          navigation: "available sections",
          contentVolume: "medium",
          visualTone: "resilient product",
        },
      },
    ],
    selectionHeuristics: {
      positivePromptSignals: [
        "error",
        "failed",
        "retry",
        "offline",
        "unavailable",
        "outage",
        "diagnostic",
        "degraded",
      ],
      negativePromptSignals: ["success", "pricing", "signup"],
      compatibleFamilies: ["app-shell", "dashboard", "data-display", "form"],
      incompatibleFamilies: ["marketing"],
    },
    designSpecHints: {
      allowedNodeTypes: ["frame", "stack", "card", "text", "button", "icon"],
      maxDepth: 6,
      responsiveBehavior: ["Keep recovery action visible on mobile.", "Avoid large technical details by default."],
    },
    shadcnHints: {
      primitives: ["Alert", "Button", "Collapsible", "Progress"],
      registryItems: ["alert", "button", "collapsible", "progress"],
      compositionNotes: ["Use Alert for message, Collapsible for details and Progress for checks."],
    },
    accessibilityNotes: ["Error text must be readable by screen readers and not rely only on color."],
  },
] satisfies ModuleDefinition[];
