import JSZip from "jszip";
import type { DesignSpec } from "@odc/shared";
import { designSpecToReact } from "./designSpecToReact";

function projectSlug(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "screen"
  );
}

/**
 * Builds the in-memory file map for a runnable Vite + React + Tailwind project
 * that renders the generated screen. Pure and deterministic for testability.
 */
export function buildViteProjectFiles(designSpec: DesignSpec): Record<string, string> {
  const slug = projectSlug(designSpec.title);
  const component = designSpecToReact(designSpec);

  return {
    "package.json": `${JSON.stringify(
      {
        name: slug,
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
        dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" },
        devDependencies: {
          "@vitejs/plugin-react": "^4.3.1",
          autoprefixer: "^10.4.20",
          postcss: "^8.4.47",
          tailwindcss: "^3.4.13",
          vite: "^5.4.8",
        },
      },
      null,
      2,
    )}\n`,
    "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(designSpec.title)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({ plugins: [react()] });
`,
    "tailwind.config.js": `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`,
    "postcss.config.js": `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
`,
    "src/index.css": `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
    "src/main.tsx": `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import GeneratedScreen from "./Screen";
import "./index.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <GeneratedScreen />
  </StrictMode>,
);
`,
    "src/Screen.tsx": component,
    "README.md": `# ${designSpec.title}

Generated by Open Design Canvas. This is a standalone Vite + React + Tailwind project.

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open the printed local URL. The screen lives in \`src/Screen.tsx\`.
`,
  };
}

export async function buildViteProjectZip(designSpec: DesignSpec): Promise<Blob> {
  const zip = new JSZip();
  const files = buildViteProjectFiles(designSpec);
  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content);
  }
  return zip.generateAsync({ type: "blob" });
}

export function viteProjectZipName(title: string): string {
  return `${projectSlug(title)}-vite.zip`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
